build.gradle.kts
helm_deploy/send-legal-mail-to-prisons-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/MagicLinkConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkEmailSender.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkEmailSenderTest.kt
src/test/resources/application-test.yml

* the email client is not being used yet - integration tests coming once it is wired up
* Kube secrets added to dev and preprod (we don't have a prod yet)

SLM-12 - add an email client to send magic link URLs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/security/CreateBarcodeUserDetailsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/security/ResourceServerConfiguration.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/E2eTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/IntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/barcode/BarcodeResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/security/CreateBarcodeUserDetailsServiceTest.kt

We now accept a `PreAuthenticatedAuthenticationToken` on header `Create-Barcode-Token`. If the token is valid - it was signed by this service and has not expired - then the token is accepted as authentication.

SLM-12 - accept JWTs created when verifying a magic link

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/SendLegalMailToPrisonsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/E2eTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/integration/magiclink/MagicLinkResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkRequestValidatorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/security/JwtServiceTest.kt

And fix a test that relies on a valid JWT

SLM-11 - Apply max email length of 254 characters

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/ErrorCodes.kt
src/main/resources/db/migration/V1_4__barcode_events_status_length.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/ErrorCodesTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/E2eTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/IntegrationTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeResourceTest.kt

* Call the random check service from the barcode check service
* Return the user that created the barcode if OK
* Return the user that created the barcode for DUPLICATE, EXPIRED and RANDOM_CHECK errors
* Rename some users to make it clearer which are external (cjsm email) or DPS (ends with _GEN)

SLM-14 apply random checks and return barcode created by

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/barcode/BarcodeResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/ErrorCodes.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/ExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkResource.kt
src/main/resources/application.yml

* Export types for returned error codes which have various data structures
* But cut the OpenAPI doc link between ErrorCode and its descendents - otherwise every possible error code appears to be available for every ErrorResponse

SLM-14 missing openapi docs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkEmailSender.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/magiclink/MagicLinkEmailSenderTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/E2eTest.kt

Updated magic link email content; including plain text and html content alternates (multipart mime)

SLM-39: Updated magic link email content

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/contact/ContactResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/contact/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/contact/ContactServiceTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/contact/ContactResourceGetContactByIdTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/contact/ContactResourceGetContactByPrisonNumberTest.kt

First of a few PRs to eventually introduce `GET /contact/{id}` which currently clashes with `GET /contact/{prisonNumber}`
* create new endpoint `GET /contact/prisonNumber/{prisonNumber}`
* deprecate `GET /contact/{prisonNumber}`
* create `GET /contact/id/{id}`

SLM-63 get contact by id

---

helm_deploy/send-legal-mail-to-prisons-api/values.yaml
helm_deploy/values-prod.yaml

It seems like the default is request=256Mi and limit=256Mi. You can see that the [bulk of apps just rely on this and are all using 256](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fc27cfedb-f5e9-45e6-9642-0fad1a5c94e7%2FresourceGroups%2Fnomisapi-t3-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-t3/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAxWMvQrCMBSFd5%252Fi0CmFDoJzFyeXOgjOcpseaCC3KTeJWvHhrfP342suSQcWCz4fvnjNNGIRJfoezYWyYqAm23DPnOCGc9vsXq6qYuFDqLzdU2Jli3GDj6lOj1uKvO6PDmNYXAnKXETXDqejtnttXCYa%252FsDPYuUHEwfuCYYAAAA%253D/timespan/P1D)

SLM-190 Specify an upper memory limit

---

.circleci/config.yml

The OWASP job is failing both in Circle and locally - we may have updated the orb and Gradle plugin out of sequence so I'm trying the cache key fix which might work in Circle. Can't explain why it's not working locally though 🤷

Fix cache key

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/config/ExceptionHandler.kt

ValidationExceptions are now logged like this:
```
2022-03-31 08:33:41.016  INFO 35060 --- [o-auto-1-exec-8] u.g.j.d.h.s.config.ExceptionHandler      : Validation exception: DUPLICATE |  
```

SLM-200: Set message field on ValidationException superclass constructor

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeServiceTest.kt
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeResourceTest.kt

This PR adds the `POST /oneTimeCode/verify` endpoint to verify a previously created one time code

SLM-230: add API to verify one time code

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeResourceTest.kt

PR to correct controller endpoint method name as I blatantly copied from another controller 🤭 ; but it also introduces a conflicting operation name in the OpenAPI docs when importing the types into a client

SLM-230: Corrected method name

---

src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/onetimecode/OneTimeCodeServiceTest.kt

PR to fix a security risk with an incomplete implementation.
When checking the OTC we retrieve it from the redis repo by sessionID - if it doesn't exist thats easy, we throw a resource not found exception.
If it does exist we then go on to check the code is the same one presented by the user. If the code matches then we delete the OTC from redis so it cant be re-used and return a JWT - happy days.
If however the OTC does exist in redis but the code presented by the user does not match, then we throw a resource not found exception and must delete the OTC from redis, to prevent it being retried.
Before this PR I'd written the code to leave the OTC in redis so that it could be retried, in readiness for a soon to be worked on ticket to allow a 3-strikes-and-out type approach.
However, without …

SLM-230: Delete OTC every time it is checked. Do not support retries

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/prisons/SupportedPrisonsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/security/ResourceServerConfiguration.kt
src/main/resources/application-dev.yml
src/main/resources/db/migration/V1_15__insert_supported_prisons.sql
src/testIntegration/kotlin/uk/gov/justice/digital/hmpps/sendlegalmailtoprisonsapi/prisons/SupportedPrisonsResourceTest.kt

* the endpoint does not contain sensitive data and is publicly visible on the unprotected start page anyway
* also useLatestVersions
* add pilot prisons to the supported prisons table
* some missing config for prison register running locally

SLM-253 Open getSupportedPrisons endpoint

---

.circleci/config.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

Similar change to https://github.com/ministryofjustice/send-legal-mail-to-prisons/pull/350. Since locking down `dev` and `preprod` environments, the Cypress smoke tests on CircleCI are failing as they can't access these.
This change adds CircleCI's IP ranges to the `allowlist` (`dev` and `preprod` only) so the smoke tests should be able to run.

Give Circle CI access to dev and preprod for the smoke tests

---

helm_deploy/send-legal-mail-to-prisons-api/values.yaml

This caused a pod to be killed with an Out Of Memory error (https://mojdt.slack.com/archives/C03KYFY11S5/p1657749656902819). Apparently there is no need to limit the pods as the limit on the JVM is all we can really control.

Don't set a hard limit on pods memory

---

build.gradle.kts

Update postgres driver dependency from 42.4.0 to 42.4.1 as a high severity vulnerability (CVE-2022-31197) is highlighted in build for postgres driver - 42.4.0 version.

Update postgres driver dependency from 42.4.0 to 42.4.1 

---

helm_deploy/send-legal-mail-to-prisons-api/values.yaml

Disable v0.47 ingress and keep only v1.2 enabled as mentioned here - 
https://github.com/ministryofjustice/hmpps-helm-charts/releases.

Disable v0.47 ingress controller

---

build.gradle.kts

Update hmpps gradle spring-boot dependency to 4.5.0 to fix security issues and other minor version dependency updates.

Update hmpps gradle spring-boot dependency to 4.5.0

---

.trivyignore
build.gradle.kts

Update hmpps spring boot version to 4.5.5 as a fix for security failures and other minor dependency updates.

Minor dependency updates

---

.trivyignore
build.gradle.kts

Upgrade hmpps.gradle-spring-boot dependency as a fix for security failures.

Upgrade dependencies as a fix for security failures.

---

helm_deploy/values-dev.yaml

Silence alerts from the dev environment outside of business hours.
Since the dev database was scheduled to turn off overnight, we get repeated alert manager notifications from the API (https://github.com/ministryofjustice/cloud-platform-environments/blob/12938dea078e35a7689bd395086e6d61d049af24/namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf#L11)
This applies the `businessHoursOnly` rule to alerts from the dev environment (documented here: https://github.com/ministryofjustice/hmpps-helm-charts/blob/4ce3afdf951a6e6b433a67cd39336a4a91901704/charts/generic-prometheus-alerts/values.yaml#L101-L102)

Silence dev alerts when not business hours

---

artillery/docker-compose.yml

SLM-334 - update SPRING_REDIS_HOST to SPRING_DATA_REDIS_HOST as a fix for failing artillery tests post update to Spring Boot 3.

SLM-334 - update SPRING_REDIS_HOST to SPRING_DATA_REDIS_HOST

---

helm_deploy/send-legal-mail-to-prisons-api/templates/barcode-stats-report-cronjob.yaml
helm_deploy/send-legal-mail-to-prisons-api/templates/cjsm-directory-cronjob.yaml
helm_deploy/send-legal-mail-to-prisons-api/values.yaml
helm_deploy/values-dev.yaml

Hopefully avoid failing cron errors because the dev database is shut down overnight and at weekends.

Reschedule dev crons to business hours

---

build.gradle.kts

Update embedded redis library as the one we have now is unsupported and the tests do not work on Macs. Replacing with a more recent version that was forked off the library we were using.
References below - 
https://github.com/kstyrc/embedded-redis/issues/135
https://stackoverflow.com/questions/53287218/java-lang-runtimeexception-cant-start-redis-server-check-logs-for-details

Update embedded redis lib

---

artillery/docker-compose.yml

Update localstack and postgres image versions to check if it fixes the failing artillery tests.

Update localstack and postgres image versions
